CREATE TABLE [Scheduling].[Recurrence] (
    [RecurrenceID]     BIGINT   IDENTITY (1, 1) NOT NULL,
    [Frequency]        INT      NULL,
    [DailyFrequency]   INT      NULL,
    [DailyDays]        INT      NULL,
	[DayOfMonth]	   INT		NULL,
    [WeeklyRecurrence] INT      NULL,
    [WeekDayMon]       BIT      NULL,
    [WeekDayTue]       BIT      NULL,
    [WeekDayWed]       BIT      NULL,
    [WeekDayThur]      BIT      NULL,
    [WeekDayFri]       BIT      NULL,
    [WeekDaySat]       BIT      NULL,
    [WeekDaySun]       BIT      NULL,
    [MonthlyFrequency] INT      NULL,
    [MonthlyDay]       INT      NULL,
    [DayMonths]        INT      NULL,
    [WeekOfMonthID]    INT      NULL,
    [DayOfWeekID]      INT      NULL,
    [TheMonths]        INT      NULL,
    [YearlyRecurrence] INT      NULL,
    [YearlyFrequency]  INT      NULL,
    [YearlyMonthID]    INT      NULL,
    [YearlyMonthOnTheID]    INT      NULL,
    [StartDate]        DATETIME NULL,
    [Ending]           INT      NULL,
    [EndAfter]         INT      NULL,
    [EndDate]          DATETIME NULL,
    [IsActive]         BIT      CONSTRAINT [DF__Recurrenc__IsAct__0F0E1094] DEFAULT ((1)) NOT NULL,
    [ModifiedBy]       INT      NOT NULL,
    [ModifiedOn]       DATETIME NOT NULL,
    [CreatedBy]        INT      NOT NULL,
    [CreatedOn]        DATETIME NOT NULL,
    CONSTRAINT [PK_RecurrenceID] PRIMARY KEY CLUSTERED ([RecurrenceID] ASC),
    CONSTRAINT [FK_Recurrence_DayOfWeek] FOREIGN KEY ([DayOfWeekID]) REFERENCES [Reference].[DayOfWeek] ([DayOfWeekID]),
    CONSTRAINT [FK_Recurrence_Month] FOREIGN KEY ([YearlyMonthID]) REFERENCES [Reference].[Month] ([MonthID]),
    CONSTRAINT [FK_Recurrence_MonthOnThe] FOREIGN KEY ([YearlyMonthOnTheID]) REFERENCES [Reference].[Month] ([MonthID]),
    CONSTRAINT [FK_Recurrence_UserCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [Core].[Users] ([UserID]),
    CONSTRAINT [FK_Recurrence_UserModifedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [Core].[Users] ([UserID]),
    CONSTRAINT [FK_Recurrence_WeekOfMonth] FOREIGN KEY ([WeekOfMonthID]) REFERENCES [Reference].[WeekOfMonth] ([WeekOfMonthID])
);



