-----------------------------------------------------------------------------------------------------------------------
-- Schema:	    Audit
-- Author:		Kyle Campbell
-- Date:		09/16/2016
--
-- Purpose:		Create Auditing Schema
--
-- Notes:		n/a (or any additional notes)
--
-- Depends:		n/a (or any dependencies such as other procs or functions)
--
-- REVISION HISTORY ---------------------------------------------------------------------------------------------------
-- 09/16/2016	Kyle Campbell	- Initial creation
-----------------------------------------------------------------------------------------------------------------------
CREATE SCHEMA [Auditing] Authorization [dbo]