-----------------------------------------------------------------------------------------------------------------------
-- Schema:	    Core
-- Author:		John Crossen
-- Date:		07/28/2015
--
-- Purpose:		Create Core Schema
--
-- Notes:		n/a (or any additional notes)
--
-- Depends:		n/a (or any dependencies such as other procs or functions)
--
-- REVISION HISTORY ---------------------------------------------------------------------------------------------------
-- 07/28/2015	John Crossen		TFS# 1015 - Initial creation.
-----------------------------------------------------------------------------------------------------------------------
CREATE SCHEMA [Core] Authorization [dbo]